[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}

[tool.poetry]
name = "beatmachine"
version = "3.1.3"
description = "A library for procedurally remixing songs"
authors = ["dhsavell <dhsavell05@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
madmom = {git = "https://github.com/CPJKU/madmom.git", rev = "805c08e69b4390ce763c098474b2f96fab47bf60"}
deprecation = "^2.0"
soundfile = "^0.10.3"
librosa = "^0.7.2"

[tool.poetry.dev-dependencies]
black = {version = "^18.3-alpha.0", allow-prereleases = true}
sphinx = "^2.2"
parameterized = "^0.7.1"
pre-commit = "^1.20"
pytest = "^5.3.5"
bump2version = "^1.0.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
